music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns=[
    url(r'^$',views.IndexView.as_view(),name = 'index'),
    url(r'^register/$',views.UserFormView.as_view(),name = 'register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view() ,name ='detail'),
    url(r'^album/add/$',views.CreateAlbum.as_view(),name="addAlbum"),
    url(r'^album/(?P<pk>[0-9]+)/$',views.UpdateAlbum.as_view(),name="updateAlbum"),
    url(r'^album/(?P<pk>[0-9]+)/delete/$',views.DeleteAlbum.as_view(),name="deleteAlbum"),

]

projectname/urls.py

from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include("music.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=10)
    genre = models.CharField(max_length=10)
    albumTitle = models.CharField(max_length=10)
    logo = models.FileField()
    isFavorite = models.BooleanField(default=False)
    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.id})
    def __str__(self):
        return "an album "+self.albumTitle

class Song(models.Model):
    fileType = models.CharField(max_length=5)
    songTitle = models.CharField(max_length=15)
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    isFavorite = models.BooleanField(default=False)
    def __str__(self):
        return self.songTitle

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields =[
            'username',
            'email',
            'password'
        ]

music/views.py
from .models import Album,Song
from django.views import generic
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect,render
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .forms import UserForm



class IndexView(generic.ListView):
    template_name = "music/index.html"
    context_object_name = "albums"

    

    def get_queryset(self):
        return Album.objects.all()



class DetailView(generic.DetailView):
    template_name = "music/detail.html"
    model = Album


class CreateAlbum(CreateView):
    model = Album
    fields = [
        'artist',
        'albumTitle',
        'genre',
        'logo'
    ]

class UpdateAlbum(UpdateView):
    model = Album
    fields = [
        'artist',
        'albumTitle',
        'genre',
        'logo'
    ]

class DeleteAlbum(DeleteView):
    model = Album
    success_url = reverse_lazy("music:index")

class UserFormView(generic.View):
    form_class = UserForm
    template_name = 'music/registration_form.html'


    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})


    def post(self,request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            user = form.save(commit = False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('music:index')
        return render(request,self.template_name,{'form':form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default"  style="background-color:rgba(0, 0, 0, 0) !important;border:1px solid rgba(0, 0, 0, 0) !important">
                <div class="panel-body"  style="background-color:rgba(0, 0, 0, 0) !important;border:1px solid rgba(0, 0, 0, 0) !important">
                    <form action="" method="post" class="form-horizontal" enctype="multipart/form-data"  style="background-color:rgba(0, 0, 0, 0) !important;border:1px solid rgba(0, 0, 0, 0) !important">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-success" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}Listen{% endblock %}</title>
    <meta charset="UTF-8"> {% load static%}
    <link rel="stylesheet" href="{% static 'music/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'music/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body style="color:white;background:url({% static 'music/images/Black-Wood-high-Quality-Background.jpg' %}) center center fixed;">
    <nav class="navbar navbar-default" style="border-radius:0px">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#topNavBar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">
                            <span style="font-family: 'Pacifico', cursive;">Listen</span>
                        </a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class= {% block albumsActive %}{% endblock %}>
                    <a href="{% url 'music:index' %}">
                                    <span class="glyphicon glyphicon-cd"></span>&nbsp; Albums
                                </a>
                </li>
                <li class= {% block songsActive %}{% endblock %}>
                    <a href="{% url 'music:index' %}">
                                    <span class="glyphicon glyphicon-music"></span>&nbsp; Songs
                                </a>
                </li>
            </ul>

            <form action="#" method="get" role="search" class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" value="" name="s" class="form-control">
                </div>
                <button class="btn btn-default" type="submit">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:addAlbum' %}">
                                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Albums
                                </a>
                </li>
                <li class="">
                    <a href="{% url 'music:index' %}">
                                    <span class="glyphicon glyphicon-off"></span>&nbsp; LogOut
                                </a>
                </li>
            </ul>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>

</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block albumsActive %}"no"{% endblock %} 
{% block songsActive %}"active"{% endblock %} 

{% block body %}

{% if errorMessage%}
<p><strong>errorMessage</strong></p>
{%endif%}

<div class="container">
    <div class="row">
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 col-xs-12" style="background-color:#0d0d0d">
            <img src="{{album.logo.url}}" class="img-responsive" alt="logo" style="">
            <h1 >{{album.albumTitle}} <span style="color:lightgrey">{{album.genre}}</span></h1>
            <h2>{{album.artist}}</h2>
        </div>
        <div class="col-lg-9 col-xl-9 col-md-9 col-sm-12 col-xs-12">
            <h3>All Songs</h3>
            <table style="width:100%">
                <tr>
                    <th>Title</th>
                    <th>Audio File</th> 
                    <th>Favorite</th>
                    <th>Action</th>
                </tr>
                {% for song in album.song_set.all %}
                <tr>
                    <td>{{song.songTitle}}</td>
                    <td>{{song.fileType}}</td>
                    <td>
                        {% if album.isFavorite %}
                            <i class="fa fa-star" aria-hidden="true" style="color:#f57900"></i>
                        {% else %}
                        <i class="fa fa-star" aria-hidden="true" style="color:grey"></i>
                        {% endif %}
                    </td>
                    <td>{{song.songTitle}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>



<!-- <form action="" method="post">
    {% csrf_token %} 
    {% for song in album.song_set.all %}
        <input type="radio" name="song" id="song{{forloop.counter}}" value="{{song.id}}">
        <label for="song{{forloop.counter}}">
            {{song.songTitle}}
            {% if song.isFavorite %}
                <img src="http://www.goldentickets.com/images/ticketutils/IMG/preferred.png" alt="">
            {% endif %}
        </label><br>
    {% endfor %}<br>
    <input type="submit" value="Favorite">
</form> -->
{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger">
                {{field.errors}}
            </span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10" style="color:black">
            {{field}}
        </div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %} {%block title%}Albums{%endblock%}
{% block albumsActive %}"active"{% endblock %} 
{% block songsActive %}"no"{% endblock %} 
{% block body %}
<div class="row">
    {% for album in albums%}
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail" style="background-color:#0d0d0d;">
            <a href="{% url 'music:detail' album.id %}"><img src="{{album.logo.url}}" alt=""></a>
            <div class="caption" style="color:white">
                <h3>{{album.albumTitle}}</h3>
                <h6>{{album.artist}}</h6>
                <span><a href="{% url 'music:detail' album.id %}" class="btn btn-primary" role="button">Details</a>
                    <button class="btn btn-default">
                        {% if album.isFavorite %}
                            <i class="fa fa-star" aria-hidden="true" style="color:#f57900"></i>
                        {% else %}
                            <i class="fa fa-star" aria-hidden="true" style="color:grey"></i>
                        {% endif %}
                    </button>
                    <form action="{% url 'music:deleteAlbum' album.id %}" method="post" style="display:inline">
                        {% csrf_token %}
                        <input type="hidden" name="albumId" value="{{album.id}}">
                        <button class="btn btn-default" type="submit">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </button>
                    </span>
                    
                </p>
            </div>
        </div>
    </div>
    {%endfor%}
</div>

<!-- <ul>
    {% for album in albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{album.albumTitle}}</a></li>
    {% endfor %}
</ul> -->

{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default"  style="background-color:rgba(0, 0, 0, 0) !important;border:1px solid rgba(0, 0, 0, 0) !important">
                <div class="panel-body"  style="background-color:rgba(0, 0, 0, 0) !important;border:1px solid rgba(0, 0, 0, 0) !important">
                    <form action="" method="post" class="form-horizontal" enctype="multipart/form-data"  style="background-color:rgba(0, 0, 0, 0) !important;border:1px solid rgba(0, 0, 0, 0) !important">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-success" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}